{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.gatewayClass.create }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ include "envoy-gateway.fullname" . }}-proxy-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy-gateway.labels" . | nindent 4 }}
spec:
  {{- with .Values.proxy.ipFamily }}
  ipFamily: {{ . }}
  {{- end }}
  provider:
    type: Kubernetes
    kubernetes:
      {{- $podSpec := include "envoy-gateway.proxy.podSpec" . | trim }}
      {{- if eq .Values.proxy.kind "DaemonSet" }}
      envoyDaemonSet:
        {{- if $podSpec }}
        pod:
          {{- $podSpec | nindent 10 }}
        {{- end }}
        container:
          image: {{ printf "%s:%s" .Values.proxy.image.repository .Values.proxy.image.tag }}
          resources:
            {{- include "envoy-gateway.proxy.resources" . | nindent 12 }}
      {{- else }}
      envoyDeployment:
        replicas: {{ .Values.proxy.replicaCount }}
        {{- if $podSpec }}
        pod:
          {{- $podSpec | nindent 10 }}
        {{- end }}
        container:
          image: {{ printf "%s:%s" .Values.proxy.image.repository .Values.proxy.image.tag }}
          resources:
            {{- include "envoy-gateway.proxy.resources" . | nindent 12 }}
      {{- if .Values.proxy.autoscaling.enabled }}
      envoyHpa:
        minReplicas: {{ .Values.proxy.autoscaling.minReplicas }}
        maxReplicas: {{ .Values.proxy.autoscaling.maxReplicas }}
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: {{ .Values.proxy.autoscaling.targetCPUUtilizationPercentage }}
      {{- end }}
      {{- end }}
      envoyService:
        type: {{ .Values.proxy.service.type }}
        {{- with .Values.proxy.service.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}


  {{- if .Values.monitoring.enabled }}
  telemetry:
    {{- if .Values.monitoring.accessLogs.enabled }}
    accessLog:
      settings:
      - format:
          type: {{ .Values.monitoring.accessLogs.format | upper }}
        sinks:
        - type: File
          file:
            path: /dev/stdout
    {{- end }}
    metrics:
      prometheus:
        disable: false
  {{- end }}
  shutdown:
    drainTimeout: 60s
    minDrainDuration: 5s
{{- end }}
