# SPDX-License-Identifier: Apache-2.0
mysql:
  enabled: false

database:
  external:
    host: mysql.example.com
    existingSecretPasswordKey: database-password

externalSecrets:
  enabled: true
  secretStoreRef:
    name: vault
  admin:
    enabled: true
    passwordRemoteRef:
      key: ci/wordpress
      property: admin-password
  database:
    enabled: true
    passwordRemoteRef:
      key: ci/wordpress
      property: database-password
