# SPDX-License-Identifier: Apache-2.0
wordpress:
  siteUrl: https://wordpress.example.com
  forceSSLAdmin: true
  disallowFileEdit: true
  disableWpCron: true
  memoryLimit: 256M
  maxMemoryLimit: 512M

service:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6

autoscaling:
  enabled: true

pdb:
  enabled: true

wpCron:
  cronJob:
    enabled: true

networkPolicy:
  enabled: true
  metrics:
    enabled: true
  egress:
    enabled: true
    allowHTTPS: true

metrics:
  enabled: true
