# SPDX-License-Identifier: Apache-2.0
plugins:
  enabled: true
  installer:
    enabled: true

objectCache:
  enabled: true
  redis:
    mode: subchart
    subchart:
      enabled: true

redis:
  architecture: standalone
  auth:
    password: ci-redis-password
  standalone:
    persistence:
      enabled: false
