# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: ghost
description: Ghost modern publishing platform and headless CMS with MySQL backend
type: application
version: 1.1.10
appVersion: "6.37.1"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - cms
  - blog
  - publishing
  - ghost
  - headless-cms
  - newsletter
  - self-hosted
icon: https://helmforge.dev/icons/charts/ghost.png
home: https://helmforge.dev
sources:
  - https://github.com/helmforgedev/charts
  - https://github.com/TryGhost/Ghost
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "upgrade to 6.37.1 (#247)"
    - kind: changed
      description: "upgrade to 6.35.0 (#190)"
  artifacthub.io/maintainers: |
    - name: HelmForge
      email: berlofa@helmforge.dev
    - name: Maicon Berlofa
      email: maicon.berloffa@gmail.com
  helmforge.dev/maturity: stable
  helmforge.dev/signed: gpg+cosign
  artifacthub.io/signKey: |
    fingerprint: 6748042FBAD8C2E11C65E564170D55148EB88A9D
    url: https://repo.helmforge.dev/pgp-public-key.asc
  helmforge.dev/repository: https://repo.helmforge.dev
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: skip-prediction
  artifacthub.io/links: |
    - name: Official Website
      url: https://ghost.org
    - name: Documentation
      url: https://helmforge.dev/docs/charts/ghost
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/ghost
    - name: support
      url: https://github.com/helmforgedev/charts/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/helmforge/mysql
dependencies:
  - name: mysql
    version: 1.8.5
    repository: oci://ghcr.io/helmforgedev/helm
    condition: mysql.enabled
