# SPDX-License-Identifier: Apache-2.0
externalSecrets:
  enabled: true
  secretStoreRef:
    name: example-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: database-url
      remoteRef:
        key: prod/hoppscotch
        property: database-url
    - secretKey: data-encryption-key
      remoteRef:
        key: prod/hoppscotch
        property: data-encryption-key
    - secretKey: webapp-server-signing-key
      remoteRef:
        key: prod/hoppscotch
        property: webapp-server-signing-key
