# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: mongodb
description: MongoDB Helm Chart - standalone, replica set, or sharded cluster using the official MongoDB image
type: application
version: 1.7.11
appVersion: "8.3.1"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - mongodb
  - database
  - nosql
  - replicaset
  - sharded
home: https://helmforge.dev
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/_/mongo
icon: https://helmforge.dev/icons/charts/mongodb.png
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "upgrade to 8.3.1 (#253)"
    - kind: fixed
      description: "fix mongodb url option for exporter pod (#257)"
  artifacthub.io/maintainers: |
    - name: HelmForge
      email: berlofa@helmforge.dev
    - name: Maicon Berlofa
      email: maicon.berloffa@gmail.com
  artifacthub.io/alternativeName: "mongo"
  helmforge.dev/maturity: stable
  helmforge.dev/signed: gpg+cosign
  artifacthub.io/signKey: |
    fingerprint: 6748042FBAD8C2E11C65E564170D55148EB88A9D
    url: https://repo.helmforge.dev/pgp-public-key.asc
  helmforge.dev/repository: https://repo.helmforge.dev
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: database
  artifacthub.io/links: |
    - name: Official Website
      url: https://www.mongodb.com
    - name: Documentation
      url: https://helmforge.dev/docs/charts/mongodb
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/mongodb
    - name: support
      url: https://github.com/helmforgedev/charts/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/helmforge/countly
