# SPDX-License-Identifier: Apache-2.0
# CI scenario: Gateway API HTTPRoute (GR-060)
postgresql:
  enabled: false

database:
  external:
    host: "postgres.example.com"
    name: metabase
    username: metabase
    password: "testpassword"

gatewayAPI:
  enabled: true
  gatewayName: my-gateway
  gatewayNamespace: default
  hostnames:
    - metabase.example.com
  path: /
  pathType: PathPrefix
