# SPDX-License-Identifier: Apache-2.0
# Install custom WordPress plugins through an idempotent post-install/post-upgrade Job

plugins:
  enabled: true
  installer:
    enabled: true
  items:
    - slug: classic-editor
      activate: true
      skipIfInstalled: true
    - slug: contact-form-7
      activate: true
      skipIfInstalled: true
