# SPDX-License-Identifier: Apache-2.0
# WordPress with ingress isolation and controlled egress

networkPolicy:
  enabled: true
  ingress:
    allowSameNamespace: true
  egress:
    enabled: true
    allowDNS: true
    allowSameNamespaceDatabase: true
    allowHTTPS: true
    allowSMTP: true
    smtpPort: 587
