# SPDX-License-Identifier: Apache-2.0
# WordPress with Redis Object Cache using HelmForge Redis subchart

plugins:
  enabled: true
  installer:
    enabled: true

objectCache:
  enabled: true
  redis:
    mode: subchart
    subchart:
      enabled: true

redis:
  architecture: standalone
  auth:
    existingSecret: wordpress-redis-auth
    existingSecretPasswordKey: redis-password
  standalone:
    persistence:
      enabled: true
      size: 8Gi
