# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: vaultwarden
description: Vaultwarden for Kubernetes with persistent SQLite storage and explicit ingress/domain configuration
type: application
version: 1.12.6
appVersion: "1.36.0"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - vaultwarden
  - bitwarden
  - password-manager
  - self-hosted
home: https://helmforge.dev/docs/charts/vaultwarden
sources:
  - https://github.com/helmforgedev/charts
  - https://github.com/dani-garcia/vaultwarden
icon: https://helmforge.dev/icons/charts/vaultwarden.png
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "upgrade to 1.36.0 (#220)"
  artifacthub.io/maintainers: |
    - name: HelmForge
      email: berlofa@helmforge.dev
    - name: Maicon Berlofa
      email: maicon.berloffa@gmail.com
  helmforge.dev/maturity: stable
  helmforge.dev/signed: gpg+cosign
  artifacthub.io/signKey: |
    fingerprint: 6748042FBAD8C2E11C65E564170D55148EB88A9D
    url: https://repo.helmforge.dev/pgp-public-key.asc
  helmforge.dev/repository: https://repo.helmforge.dev
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: security
  artifacthub.io/links: |
    - name: Official Website
      url: https://github.com/dani-garcia/vaultwarden
    - name: Documentation
      url: https://helmforge.dev/docs/charts/vaultwarden
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/vaultwarden
    - name: support
      url: https://github.com/helmforgedev/charts/issues
dependencies:
  - name: postgresql
    version: 1.10.0
    repository: oci://ghcr.io/helmforgedev/helm
    condition: postgresql.enabled
  - name: mysql
    version: 1.9.1
    repository: oci://ghcr.io/helmforgedev/helm
    condition: mysql.enabled
